# Generated by Django 2.0.6 on 2018-06-22 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_app', '0002_auto_20180622_1411'),
        ('loan_app', '0002_auto_20180622_1744'),
    ]

    operations = [
        migrations.AddField(
            model_name='loantype',
            name='client_classes',
            field=models.ManyToManyField(to='profile_app.ClientClass'),
        ),
    ]
