# Generated by Django 2.0.6 on 2018-06-25 14:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('loan_app', '0004_loantype_penalty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='expected_payment',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='loan',
            name='given',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='loan',
            name='profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='profile_app.Profile'),
        ),
        migrations.AlterField(
            model_name='loan',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='loan_app.Status'),
        ),
        migrations.AlterField(
            model_name='loan',
            name='type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='loan_app.LoanType'),
        ),
    ]
