# Generated by Django 2.0.6 on 2018-06-26 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan_app', '0008_auto_20180626_1049'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='amount_remain',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
